version: '3'
services:
    web:
        image: nginx:1.15.12-alpine
        container_name: web
        hostname: web
        domainname: docker.local
        volumes:
            - "./files/nginx/default:/etc/nginx/conf.d/default.conf"
        env_file:
            - ".env"
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        #command: /bin/sh -c "envsubst '$NGINX_HOST' && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
            - apache
        networks:
            - app-network
    apache:
        image: httpd:latest
        container_name: apache
        hostname: apache
        domainname: docker.local
        volumes:
            - "./files/apache/default.conf:/usr/local/apache2/conf/httpd.conf"
            - "./wordpress/:/usr/local/apache2/htdocs/wordpress/"
        env_file:
            - ".env"
        ports:
            - "8080:8080"
#        environment:
#            - APACHE_HOST=${NGINX_HOST}
#        command: /bin/sh -c "envsubst '$APACHE_HOST' && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
        networks:
            - app-network
    php:
        image: webdevops/php
        restart: always
        volumes:
#            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./wordpress:/usr/local/apache2/htdocs/wordpress/"
        env_file:
            - ".env"
        ports:
            - "9000:9000"
        networks:
            - app-network
    mysqldb:
        image: mysql:8.0.21
        container_name: mysqldb
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        # env_file:
        #     - ".env"
        environment:
            - MYSQL_DATABASE=wordpress
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=wp
            - MYSQL_PASSWORD=wp
            - MYSQL_ROOT_HOST=%
        ports:
            - "3306:3306"
        volumes:
            - "./db/mysql:/var/lib/mysql"
            - "./files/mysql/50-my.cnf:/etc/mysql/my.cnf"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
        ## test for begin build 
